/**
 * Help text constants for slash commands.
 * Extracted so they can be independently tested without importing server.ts.
 */

export const HELP_TEXTS: Record<string, string> = {
  '/help': [
    '📖 Available slash commands',
    'Tip: run any command with --help for details, e.g. /session --help',
    '',
    '── Basics ──',
    '  /help                        — Show this message',
    '  /status                      — Show current session info + bot health (uptime, RSS)',
    '',
    '── Conversation sessions ──',
    '  /new                         — Start a new manual session in this group chat',
    '  /reset                       — Return this group chat to its main session',
    '  /session list                — List all sessions for this chat',
    '  /session use <id>            — Switch to a different session',
    '  /close                       — Archive current session and remove its worktree if any',
    '',
    '── Context ──',
    '  /compact                     — Compact session context (reduce token usage)',
    '  /forget <keyword>            — Delete memory entries matching keyword',
    '',
    '── Owner only: maintenance ──',
    '  /schedule <time> <goal>      — Schedule a future self-dev task',
    '  /merge-pr                    — Merge the PR/MR for this session (squash + delete branch)',
    '  /session worktrees           — List self-dev worktrees (not chat session switching)',
    '  /session clean               — Auto-clean merged + orphan worktrees',
    '  /session clean <id>          — Remove a specific worktree',
    '  /clean-task [--chat] [--dry-run] [--days N] — Remove retained completed tasks from board',
    '',
    '── Owner only: chat configuration ──',
    '  /chat init                  — Initialize chat config and task board',
    '  /chat status                — Show chat workdir/task board config',
    '  /chat memory status         — Show chat-level memory config',
    '  /chat memory enable         — Enable chat-level memory injection',
    '  /chat memory disable        — Disable chat-level memory injection',
    '  /chat set-workdir <path>    — Set default absolute workdir for new sessions',
    '  /chat clear-workdir         — Clear chat default workdir',
    '',
    '── Agents ──',
    '  /agent list                 — List active agents',
    '  /agent info <handle>        — Show agent details and bot binding',
    '  /agent sync                 — Sync registry/agents manifests (MANAGE_AGENTS or owner)',
    '  /agent bind-bot <handle> <app_id> — Bind an agent to a Feishu app bot',
    '  /agent unbind-bot <handle>  — Disable an agent bot binding',
    '  /agent default <handle>     — Set chat default agent',
    '',
    '── Owner only: projects ──',
    '',
    '  /project                     — Show session project',
    '  /project list                — List all registered projects',
    '  /project add <name> <path>   — Register a project',
    '  /project remove <name>       — Unregister a project',
    '  /project use <name>          — Bind session to a project',
    '  /project clear               — Detach session from project',
    '',
    '── Owner only: task board ──',
    '  /add-bot @bot                — Share this chat task board with another bot',
    '',
    '── Remote execution machines ──',
    '  Machines are paired and bound to chats in the admin console (执行机器).',
    '  Open the console → Machines to generate a pairing token and connect a daemon.',
  ].join('\n'),

  '/new': [
    '/new — Start a new manual session in this group chat',
    '',
    'Usage: /new',
    '',
    'Creates a fresh manual session and makes it active for this group chat for 24 hours.',
    'Use /reset to return to the main chat session.',
  ].join('\n'),

  '/reset': [
    '/reset — Return this group chat to its main session',
    '',
    'Usage: /reset',
    '',
    'Clears the active manual-session pointer and routes future root messages',
    'back to the main group-chat session.',
  ].join('\n'),

  '/status': [
    '/status — Show current session info and bot health',
    '',
    'Usage: /status',
    '',
    'Displays: session key, scope, status, message count, created date,',
    'plus process uptime and memory usage (RSS). Health lines are shown',
    'even when no session exists yet, so /status doubles as a liveness probe.',
  ].join('\n'),

  '/session': [
    '/session — Manage conversation sessions and self-dev worktrees',
    '',
    'Usage:',
    '  /session list          — List all sessions for this chat',
    '  /session use <id>      — Switch to a different session by ID prefix',
    '',
    'Owner only:',
    '  /session worktrees     — List sessions with self-dev worktrees (shows task goal)',
    '  /session clean         — Auto-clean: merged PR + orphan DB + orphan disk',
    '  /session clean --all   — Force remove ALL worktrees (regardless of merge status)',
    '  /session clean <id>    — Remove a specific worktree by session ID prefix',
    '',
    'Merge detection uses GitHub PR status (covers rebase/squash merge).',
    'External-project direct paths are never auto-deleted; only managed git worktrees are eligible.',
    '',
    'Related:',
    '  /new                   — Start a fresh manual session',
    '  /reset                 — Return to the main chat session',
  ].join('\n'),

  '/close': [
    '/close — Archive the current session',
    '',
    'Usage: /close',
    '',
    'Archives the current session and removes its managed git worktree if one exists.',
    'Use /session clean for owner-only cleanup across self-dev worktrees.',
  ].join('\n'),

  '/compact': [
    '/compact — Compact session context to reduce token usage',
    '',
    'Usage: /compact',
    '',
    'Removes all stored messages for the current session and reports',
    'how many messages were removed and the token reduction.',
  ].join('\n'),

  '/forget': [
    '/forget — Delete memory entries matching a keyword',
    '',
    'Usage: /forget <keyword>',
    '',
    'Removes all memory entries whose content contains <keyword>.',
    'Returns the count of deleted entries.',
  ].join('\n'),

  '/schedule': [
    '/schedule — Schedule a self-dev task to run at a future time (owner only)',
    '',
    'Usage: /schedule <time> <goal>',
    '',
    'Supported time expressions:',
    '  N分钟后 <goal>               — N minutes from now',
    '  N小时后 <goal>               — N hours from now',
    '  今天/今晚 HH点 <goal>         — Today at HH:00 (rolls to tomorrow if past)',
    '  明天 HH点 <goal>             — Tomorrow at HH:00',
    '  2026-03-25T09:00:00 <goal>  — ISO-8601 timestamp',
    '',
    'Examples:',
    '  /schedule 明天9点 implement multi-turn-conversation',
    '  /schedule 2小时后 add user authentication',
    '  /schedule 30分钟后 fix login bug',
  ].join('\n'),

  '/chat': [
    '/chat — Manage current group chat configuration (owner only)',
    '',
    'Usage:',
    '  /chat init                         — Initialize chat config and task board',
    '  /chat status                       — Show workdir and task board',
    '  /chat memory status                — Show chat-level memory config',
    '  /chat memory enable                — Enable memory injection',
    '  /chat memory disable               — Disable memory injection',
    '  /chat set-workdir <absolute-path>  — Set default workdir for new sessions',
    '  /chat clear-workdir                — Clear default workdir',
    '',
    'Chat defaults are applied only when a new session is created.',
    'Existing sessions keep their current workspace state.',
  ].join('\n'),

  '/agent': [
    '/agent — Manage OpenClaudeTag agents',
    '',
    'Usage:',
    '  /agent list',
    '  /agent info <handle>',
    '  /agent sync',
    '  /agent bind-bot <handle> <app_id>',
    '  /agent unbind-bot <handle>',
    '  /agent default <handle>',
    '',
    'Mutating commands require MANAGE_AGENTS or owner role.',
  ].join('\n'),

  '/add-bot': [
    '/add-bot — Share the current group task board with another Feishu bot (owner only)',
    '',
    'Usage: /add-bot @new-bot',
    '',
    'Requires this group to have already run /chat init. Adds the mentioned bot as',
    'a tasklist collaborator and posts an internal @ configuration message in',
    'the current group/thread so it can use the same chat task-tracking space.',
  ].join('\n'),

  '/clean-task': [
    '/clean-task — Remove completed Feishu tasks after the retention window (owner only)',
    '',
    'Usage:',
    '  /clean-task                  — Clean completed tasks linked to the current session',
    '  /clean-task --chat           — Clean completed tasks from this chat task board',
    '  /clean-task --dry-run        — Preview the cleanup without removing tasks',
    '  /clean-task --days N         — Override the retention window for this run',
    '',
    'Completed tasks are removed from the task board with remove_tasklist; task records are not deleted.',
    'Default retention is OPEN_TAG_FEISHU_TASK_RETENTION_DAYS, or 7 days when unset.',
  ].join('\n'),

  '/project': [
    '/project — Manage project registry for the session (owner only)',
    '',
    'Usage:',
    '  /project                    — Show the project currently bound to this session',
    '  /project list               — List all registered projects',
    '  /project add <name> <path>  — Register a local directory as a named project',
    '  /project remove <name>      — Unregister a project',
    '  /project use <name>         — Bind this session to a project',
    '  /project clear              — Detach the session from its current project',
  ].join('\n'),

  '/merge-pr': [
    '/merge-pr — Merge the PR/MR associated with this session (owner only)',
    '',
    'Usage: /merge-pr',
    '',
    'Squash merges the PR/MR linked to the current session and deletes the branch.',
    'The PR/MR URL must already be associated with the current session.',
    'After a successful merge, merged worktrees are automatically cleaned up.',
  ].join('\n'),

};

export const HELP_TEXTS_ZH: Record<string, string> = {
  '/help': [
    '📖 可用斜杠命令',
    '提示：任意命令都可加上 --help 查看详情，例如 /session --help',
    '',
    '── 基础 ──',
    '  /help                        — 查看这条帮助',
    '  /status                      — 查看当前会话信息 + 机器人健康状态（uptime、RSS）',
    '',
    '── 会话 ──',
    '  /new                         — 在当前群聊启动一个新的手动 session',
    '  /reset                       — 回到当前群聊的 main session',
    '  /session list                — 列出当前聊天的所有会话',
    '  /session use <id>            — 切换到其他会话',
    '  /close                       — 归档当前 session，并移除关联 worktree（如有）',
    '',
    '── 上下文 ──',
    '  /compact                     — 压缩当前会话上下文（减少 token 使用）',
    '  /forget <keyword>            — 删除匹配关键字的记忆',
    '',
    '── 仅 owner：维护 ──',
    '  /schedule <time> <goal>      — 调度一条未来执行的自迭代任务',
    '  /merge-pr                    — 合并当前 session 关联的 PR/MR（squash + 删分支）',
    '  /session worktrees           — 列出自迭代 worktree（不是聊天 session 切换）',
    '  /session clean               — 自动清理已合并和孤儿 worktree',
    '  /session clean <id>          — 删除指定 worktree',
    '  /clean-task [--chat] [--dry-run] [--days N] — 移出保留期后的已完成任务',
    '',
    '── 仅 owner：群聊配置 ──',
    '  /chat init                  — 初始化群聊配置和任务看板',
    '  /chat status                — 查看群聊工作目录/任务看板配置',
    '  /chat memory status         — 查看群聊记忆状态',
    '  /chat memory enable         — 开启群聊记忆',
    '  /chat memory disable        — 关闭群聊记忆',
    '  /chat set-workdir <path>    — 设置新 session 默认绝对工作目录',
    '  /chat clear-workdir         — 清除群聊默认工作目录',
    '',
    '── Agents ──',
    '  /agent list                 — 列出活跃 agent',
    '  /agent info <handle>        — 查看 agent 详情和 bot 绑定',
    '  /agent sync                 — 同步 registry/agents manifests（需 MANAGE_AGENTS 或 owner）',
    '  /agent bind-bot <handle> <app_id> — 将 agent 绑定到飞书应用机器人',
    '  /agent unbind-bot <handle>  — 禁用 agent bot 绑定',
    '  /agent default <handle>     — 设置当前群聊默认 agent',
    '',
    '── 仅 owner：项目 ──',
    '',
    '  /project                     — 查看当前 session 绑定的项目',
    '  /project list                — 列出已注册项目',
    '  /project add <name> <path>   — 注册项目',
    '  /project remove <name>       — 删除项目注册',
    '  /project use <name>          — 将当前 session 绑定到项目',
    '  /project clear               — 解除 session 项目绑定',
    '',
    '── 仅 owner：任务看板 ──',
    '  /add-bot @bot                — 让另一个机器人共享当前群任务看板',
    '',
    '── 远程执行机器 ──',
    '  机器在管理控制台（执行机器）中配对并绑定到群聊。',
    '  打开控制台 → 执行机器，生成配对 token 并连接 daemon。',
  ].join('\n'),

  '/new': [
    '/new — 在当前群聊启动一个新的手动 session',
    '',
    '用法：/new',
    '',
    '创建一个新的手动 session，并在 24 小时内设为当前群聊的活跃 session。',
    '使用 /reset 可回到 main session。',
  ].join('\n'),

  '/reset': [
    '/reset — 回到当前群聊的 main session',
    '',
    '用法：/reset',
    '',
    '清除当前群聊的手动 session 指针，后续根消息会重新路由到 main session。',
  ].join('\n'),

  '/status': [
    '/status — 查看当前会话信息和机器人健康状态',
    '',
    '用法：/status',
    '',
    '显示：session key、scope、status、message 数、created date，',
    '以及进程 uptime 和内存使用（RSS）。没有会话时也会返回健康信息，',
    '因此 /status 也可用作存活探测。',
  ].join('\n'),

  '/session': [
    '/session — 管理会话与自迭代 worktree',
    '',
    '用法：',
    '  /session list          — 列出当前聊天的所有会话',
    '  /session use <id>      — 按 ID 前缀切换会话',
    '',
    '仅 owner：',
    '  /session worktrees     — 列出有 worktree 的 sessions（显示 task goal）',
    '  /session clean         — 自动清理：已合并 PR + 孤儿 DB + 孤儿磁盘目录',
    '  /session clean --all   — 强制删除所有 worktree（无论是否已合并）',
    '  /session clean <id>    — 按 session ID 前缀删除指定 worktree',
    '',
    '合并检测基于 GitHub PR 状态（覆盖 rebase/squash merge）。',
    'external project 的 direct path 永远不会被自动删除；只有受管 git worktree 会进入自动清理。',
    '',
    '相关：',
    '  /new                   — 启动新的手动 session',
    '  /reset                 — 回到 main session',
  ].join('\n'),

  '/close': [
    '/close — 归档当前 session',
    '',
    '用法：/close',
    '',
    '归档当前 session，并移除它关联的受管 git worktree（如存在）。',
    '跨自迭代 worktree 的清理请使用 owner-only 的 /session clean。',
  ].join('\n'),

  '/compact': [
    '/compact — 压缩当前会话上下文，减少 token 使用',
    '',
    '用法：/compact',
    '',
    '删除当前会话已存储的消息，并返回删除条数与 token 缩减情况。',
  ].join('\n'),

  '/forget': [
    '/forget — 删除匹配关键字的记忆',
    '',
    '用法：/forget <keyword>',
    '',
    '删除内容中包含 <keyword> 的记忆，并返回删除数量。',
  ].join('\n'),

  '/schedule': [
    '/schedule — 调度一条未来执行的自迭代任务（仅 owner）',
    '',
    '用法：/schedule <time> <goal>',
    '',
    '支持的时间表达式：',
    '  N分钟后 <goal>               — 从现在起 N 分钟后',
    '  N小时后 <goal>               — 从现在起 N 小时后',
    '  今天/今晚 HH点 <goal>         — 今天 HH:00（若已过则顺延到明天）',
    '  明天 HH点 <goal>             — 明天 HH:00',
    '  2026-03-25T09:00:00 <goal>  — ISO-8601 时间戳',
    '',
    '示例：',
    '  /schedule 明天9点 implement multi-turn-conversation',
    '  /schedule 2小时后 add user authentication',
    '  /schedule 30分钟后 fix login bug',
  ].join('\n'),

  '/chat': [
    '/chat — 管理当前群聊配置（仅 owner）',
    '',
    '用法：',
    '  /chat init                         — 初始化群聊配置和任务看板',
    '  /chat status                       — 查看工作目录和任务看板',
    '  /chat memory status                — 查看群聊记忆状态',
    '  /chat memory enable                — 开启群聊记忆',
    '  /chat memory disable               — 关闭群聊记忆',
    '  /chat set-workdir <absolute-path>  — 设置新 session 默认工作目录',
    '  /chat clear-workdir                — 清除默认工作目录',
    '',
    '群聊默认值只在新 session 创建时生效。',
    '已有 session 会保留当前 workspace 状态。',
  ].join('\n'),

  '/agent': [
    '/agent — 管理 OpenClaudeTag agents',
    '',
    '用法：',
    '  /agent list',
    '  /agent info <handle>',
    '  /agent sync',
    '  /agent bind-bot <handle> <app_id>',
    '  /agent unbind-bot <handle>',
    '  /agent default <handle>',
    '',
    '变更类命令需要 MANAGE_AGENTS 或 owner 角色。',
  ].join('\n'),

  '/add-bot': [
    '/add-bot — 让另一个飞书机器人共享当前群的任务看板（仅 owner）',
    '',
    '用法：/add-bot @新的机器人',
    '',
    '要求当前群已执行过 /chat init。命令会把被 mention 的机器人加入 tasklist 协作人，',
    '并在当前群聊/话题内 @ 它发送内部任务看板配置消息，让它使用同一个群聊任务跟踪配置。',
  ].join('\n'),

  '/clean-task': [
    '/clean-task — 按保留期移出已完成的飞书任务（仅 owner）',
    '',
    '用法：',
    '  /clean-task                  — 清理当前 session 关联的已完成任务',
    '  /clean-task --chat           — 清理当前群任务看板中的已完成任务',
    '  /clean-task --dry-run        — 只预览，不移出任务',
    '  /clean-task --days N         — 本次执行覆盖保留天数',
    '',
    '清理使用 remove_tasklist 从任务看板移出任务，不删除任务本体。',
    '默认保留期来自 OPEN_TAG_FEISHU_TASK_RETENTION_DAYS，未配置时为 7 天。',
  ].join('\n'),

  '/project': [
    '/project — 管理当前 session 的项目绑定（仅 owner）',
    '',
    '用法：',
    '  /project                    — 查看当前 session 绑定的项目',
    '  /project list               — 列出已注册项目',
    '  /project add <name> <path>  — 注册本地目录为项目',
    '  /project remove <name>      — 删除项目注册',
    '  /project use <name>         — 将当前 session 绑定到项目',
    '  /project clear              — 解除当前项目绑定',
  ].join('\n'),

  '/merge-pr': [
    '/merge-pr — 合并当前 session 关联的 PR/MR（仅 owner）',
    '',
    '用法：/merge-pr',
    '',
    '对当前 session 关联的 PR/MR 执行 squash merge 并删除分支。',
    'PR/MR URL 必须已经关联到当前 session。',
    '合并成功后会自动清理已合并的 worktree。',
  ].join('\n'),

};

export function getHelpText(command: string, replyLanguage: 'zh-CN' | 'en-US' = 'en-US'): string {
  if (replyLanguage === 'zh-CN') {
    return HELP_TEXTS_ZH[command] ?? HELP_TEXTS[command] ?? '';
  }

  return HELP_TEXTS[command] ?? '';
}
